FROM openjdk:8-jre-alpine3.7
MAINTAINER Magenta Swamp Blaster

ADD ./target/webshop.authserver-0.0.1-SNAPSHOT.jar /home
CMD ["java", "-jar", "/home/webshop.authserver-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080
